spring.application.name=springJDBC

spring.datasource.url = jdbc:postgresql://ep-dawn-hill-b3egy1ni-pooler.c-4.ap-southeast-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_byunG85PTkqB&sslmode=require&channelBinding=require
spring.datasource.username = neondb_owner
spring.datasource.password = npg_byunG85PTkqB
# spring.datasource.driver-class-name=org.postgresql.Driver
